spring.application.name=recipe-finder
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_finder_db
spring.datasource.username=postgres
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Server
server.port=8181
server.servlet.context-path=/api

# Logging
logging.level.root=INFO
logging.level.com.recipefinder=DEBUG
